### ISSUE TITLE
[FEATURE] allow to configure the CommandsConsumer to have a timeout

### ISSUE THREAD

**Issue by juan-medina** [LearningByExample/kotlin-event-driven-petstore#14]
**Describe the feature**
When we use the CommandsConsumer if Kafka is not available we will wait forever.

**Additional context**
We should be able to configure how long we will wait that is available before subscribing to get commands.

**Comment by juan-medina** [comment]
@FanyCastro update your project and add to the pet-commands ms the need configuration for timeout:

```yaml
service:
    commands:
        consumer:
            bootstrap-server: localhost:9092
            topic: pet-commands
            client-id: pet_commands_consumer
            group-id: pet_commands_consumers
            offset-earliest: earliest
            timeout-ms: 500

```
